# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.chime_tts_renewed: debug

homeassistant:
  media_dirs:
    local: /workspaces/chime_tts_renewed/media
  allowlist_external_dirs:
    - "/workspaces/chime_tts_renewed/media"
    - "/workspaces/chime_tts_renewed/config/www"

media_source:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

tts:
  - platform: google_translate
    service_name: google_say
